{
 "title": "1.12 DC/OS Local Kafka Dashboard",
 "description": "Example of a Selectable Local Kafka Dashboard for DC/OS 1.12\n\n- For Developers: Parameterized to an input-able Kafka Cluster Name\n- Only displays metrics for Brokers and Topics within a specified Kafka cluster\n",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "servicename",
    "label": "Kafka Cluster Name:",
    "query": "kafka_app_info_version{executor_name=\"kafka\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Local Kafka Overview for $servicename",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Cluster avg msg/sec (1m)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_messagesinpersec_1minuterate{service_name=~\"$servicename\"})by(service_name)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Cluster avg msg/sec (5m)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_messagesinpersec_5minuterate{service_name=~\"$servicename\"})by(service_name)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Cluster avg msg/sec (15m)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_messagesinpersec_15minuterate{service_name=~\"$servicename\"})by(service_name)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Cluster avg msg/sec (1m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_messagesinpersec_1minuterate{service_name=~\"$servicename\"})by(service_name)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Cluster avg msg/sec (5m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_messagesinpersec_5minuterate{service_name=~\"$servicename\"})by(service_name)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Cluster avg msg/sec (15m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_messagesinpersec_15minuterate{service_name=~\"$servicename\"})by(service_name)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Disk Used per Agent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "max by(instance)(disk_used)", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Cluster avg msg/sec (1m) by Topic",
   "type": "graph",
   "description": "Average messages per second per Topic",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_messagesinpersec_1minuterate{service_name=~\"$servicename\"})by(topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Cluster avg msg/sec (5m) by Topic",
   "type": "graph",
   "description": "Average messages per second per Topic",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_messagesinpersec_5minuterate{service_name=~\"$servicename\"})by(topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Cluster avg msg/sec (15m) by Topic",
   "type": "graph",
   "description": "Average messages per second per Topic",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_messagesinpersec_15minuterate{service_name=~\"$servicename\"})by(topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Number of Leaders per Broker",
   "type": "graph",
   "description": "Number of leaders on this broker. This should be mostly even across all brokers. If not, set auto.leader.rebalance.enable to true on all brokers in the cluster.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kafka_server_replicamanager_leadercount{service_name=~\"$servicename\"}",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Heap Memory in Use",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "go_memstats_heap_inuse_bytes", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Partition Count Across Brokers",
   "type": "graph",
   "description": "Number of partitions on this broker. This should be mostly even across all brokers.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_replicamanager_partitioncount{service_name=~\"$servicename\"}",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  { "title": "Broker Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "ActiveControllerCount",
   "type": "singlestat",
   "description": "The first node to boot in a Kafka cluster automatically becomes the controller, and there can be only one. The controller in a Kafka cluster is responsible for maintaining the list of partition leaders, and coordinating leadership transitions (in the event a partition leader becomes unavailable). If it becomes necessary to replace the controller, a new controller is randomly chosen by ZooKeeper from the pool of brokers. In general, it is not possible for this value to be greater than one, but you should definitely alert on a value of zero that lasts for more than a short period (< 1s) of time.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 46 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount{service_name=~\"$servicename\"})by(service_name)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "singlestat",
   "description": "In a healthy cluster, the number of in sync replicas (ISRs) should be exactly equal to the total number of replicas. If partition replicas fall too far behind their leaders, the follower partition is removed from the ISR pool, and you should see a corresponding increase in IsrShrinksPerSec. Since Kafka’s high-availability guarantees cannot be met without replication, investigation is certainly warranted should this metric value exceed zero for extended time periods.\n\nIf this metric has a value greater than 1 it means that data is not being replicated to enough number of brokers thereby increasing the probability of data loss.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 46 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kafka_cluster_partition_underreplicated{service_name=~\"$servicename\"})by(service_name)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 46 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kafka_controller_kafkacontroller_offlinepartitionscount)"
    }
   ]
  },
  {
   "title": "Total Partition Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 46 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_globalpartitioncount{service_name=~\"$servicename\"})",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "ISR Expansion Rate",
   "type": "singlestat",
   "description": "The number of in-sync replicas (ISRs) for a particular partition should remain fairly static, the only exceptions are when you are expanding your broker cluster or removing partitions. In order to maintain high availability, a healthy Kafka cluster requires a minimum number of ISRs for failover. A replica could be removed from the ISR pool for a couple of reasons: it is too far behind the leader’s offset (user-configurable by setting the replica.lag.max.messages configuration parameter), or it has not contacted the leader for some time (configurable with the replica.socket.timeout.ms parameter). No matter the reason, an increase in IsrShrinksPerSec without a corresponding increase in IsrExpandsPerSec shortly thereafter is cause for concern and requires user intervention.The Kafka documentation provides a wealth of information on the user-configurable parameters for brokers.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 46 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_isrexpandspersec_5minuterate{service_name=~\"$servicename\"})",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "ISR Shrink Rate",
   "type": "singlestat",
   "description": "The number of in-sync replicas (ISRs) for a particular partition should remain fairly static, the only exceptions are when you are expanding your broker cluster or removing partitions. In order to maintain high availability, a healthy Kafka cluster requires a minimum number of ISRs for failover. A replica could be removed from the ISR pool for a couple of reasons: it is too far behind the leader’s offset (user-configurable by setting the replica.lag.max.messages configuration parameter), or it has not contacted the leader for some time (configurable with the replica.socket.timeout.ms parameter). No matter the reason, an increase in IsrShrinksPerSec without a corresponding increase in IsrExpandsPerSec shortly thereafter is cause for concern and requires user intervention.The Kafka documentation provides a wealth of information on the user-configurable parameters for brokers.",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 46 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_isrshrinkspersec_5minuterate{service_name=~\"$servicename\"})",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Producer Purgatory Requests Waiting",
   "type": "singlestat",
   "description": "Number of requests waiting in the producer purgatory. This should be non-zero when acks=all is used on the producer.",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 46 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_delayedoperationpurgatory_numdelayedoperations{service_name=~\"$servicename\"})",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Delayed Fetch Operation Purgatory Size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 46 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kafka_server_delayedoperationpurgatory_purgatorysize{service_name=~\"$servicename\"})",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Total Partition Count per Broker",
   "type": "graph",
   "description": "The first node to boot in a Kafka cluster automatically becomes the controller, and there can be only one. The controller in a Kafka cluster is responsible for maintaining the list of partition leaders, and coordinating leadership transitions (in the event a partition leader becomes unavailable). If it becomes necessary to replace the controller, a new controller is randomly chosen by ZooKeeper from the pool of brokers. In general, it is not possible for this value to be greater than one, but you should definitely alert on a value of zero that lasts for more than a short period (< 1s) of time.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_globalpartitioncount{service_name=~\"$servicename\"}",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "ISR Expansion Rate per Broker",
   "type": "graph",
   "description": "The number of in-sync replicas (ISRs) for a particular partition should remain fairly static, the only exceptions are when you are expanding your broker cluster or removing partitions. In order to maintain high availability, a healthy Kafka cluster requires a minimum number of ISRs for failover. A replica could be removed from the ISR pool for a couple of reasons: it is too far behind the leader’s offset (user-configurable by setting the replica.lag.max.messages configuration parameter), or it has not contacted the leader for some time (configurable with the replica.socket.timeout.ms parameter). No matter the reason, an increase in IsrShrinksPerSec without a corresponding increase in IsrExpandsPerSec shortly thereafter is cause for concern and requires user intervention.The Kafka documentation provides a wealth of information on the user-configurable parameters for brokers.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_replicamanager_isrexpandspersec_5minuterate{service_name=~\"$servicename\"}",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "ISR Shrink Rate per Broker",
   "type": "graph",
   "description": "The number of in-sync replicas (ISRs) for a particular partition should remain fairly static, the only exceptions are when you are expanding your broker cluster or removing partitions. In order to maintain high availability, a healthy Kafka cluster requires a minimum number of ISRs for failover. A replica could be removed from the ISR pool for a couple of reasons: it is too far behind the leader’s offset (user-configurable by setting the replica.lag.max.messages configuration parameter), or it has not contacted the leader for some time (configurable with the replica.socket.timeout.ms parameter). No matter the reason, an increase in IsrShrinksPerSec without a corresponding increase in IsrExpandsPerSec shortly thereafter is cause for concern and requires user intervention.The Kafka documentation provides a wealth of information on the user-configurable parameters for brokers.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_replicamanager_isrshrinkspersec_5minuterate{service_name=~\"$servicename\"}",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Producer Purgatory Requests Waiting per Broker",
   "type": "graph",
   "description": "Number of requests waiting in the producer purgatory. This should be non-zero when acks=all is used on the producer.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_delayedoperationpurgatory_numdelayedoperations{service_name=~\"$servicename\"})by(task_name)",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Offline Partitions per Broker",
   "type": "graph",
   "description": "This value should be 0",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(kafka_controller_kafkacontroller_offlinepartitionscount{service_name=~\"$servicename\"})by(task_name)",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Delayed Fetch Operation Purgatory Size by Broker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 57 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_delayedoperationpurgatory_purgatorysize{service_name=~\"$servicename\"})by(task_name)",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Kafka avg msg/sec (1m) per Broker",
   "type": "graph",
   "description": "Average messages per second per Kafka broker",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_messagesinpersec_1minuterate{service_name=~\"$servicename\"})by(task_name)",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Kafka avg msg/sec (5m) per Broker",
   "type": "graph",
   "description": "Average messages per second per Kafka broker",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_messagesinpersec_5minuterate{service_name=~\"$servicename\"})by(task_name)",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Kafka avg msg/sec (15m) per Broker",
   "type": "graph",
   "description": "Average messages per second per Kafka broker",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_messagesinpersec_15minuterate{service_name=~\"$servicename\"})by(task_name)",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "All Bytes In (1min) per Broker",
   "type": "graph",
   "description": "Generally, disk throughput tends to be the main bottleneck in Kafka performance. However, that’s not to say that the network is never a bottleneck. Depending on your use case, hardware, and configuration, the network can quickly become the slowest segment of a message’s trip, especially if you are sending messages across data centers. Tracking network throughput on your brokers gives you more information as to where potential bottlenecks may lie, and can inform decisions like whether or not you should enable end-to-end compression of your messages.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_bytesinpersec_all_1minuterate{service_name=~\"$servicename\"})by(task_name)",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "All Bytes Out (1min) per Broker",
   "type": "graph",
   "description": "Generally, disk throughput tends to be the main bottleneck in Kafka performance. However, that’s not to say that the network is never a bottleneck. Depending on your use case, hardware, and configuration, the network can quickly become the slowest segment of a message’s trip, especially if you are sending messages across data centers. Tracking network throughput on your brokers gives you more information as to where potential bottlenecks may lie, and can inform decisions like whether or not you should enable end-to-end compression of your messages.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_bytesoutpersec_all_1minuterate{service_name=~\"$servicename\"})by(task_name)",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "All Bytes In (15min) per Broker",
   "type": "graph",
   "description": "Generally, disk throughput tends to be the main bottleneck in Kafka performance. However, that’s not to say that the network is never a bottleneck. Depending on your use case, hardware, and configuration, the network can quickly become the slowest segment of a message’s trip, especially if you are sending messages across data centers. Tracking network throughput on your brokers gives you more information as to where potential bottlenecks may lie, and can inform decisions like whether or not you should enable end-to-end compression of your messages.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_bytesinpersec_all_15minuterate{service_name=~\"$servicename\"})by(task_name)",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "All Bytes Out (15min) per (Service / Broker)",
   "type": "graph",
   "description": "Generally, disk throughput tends to be the main bottleneck in Kafka performance. However, that’s not to say that the network is never a bottleneck. Depending on your use case, hardware, and configuration, the network can quickly become the slowest segment of a message’s trip, especially if you are sending messages across data centers. Tracking network throughput on your brokers gives you more information as to where potential bottlenecks may lie, and can inform decisions like whether or not you should enable end-to-end compression of your messages.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_bytesoutpersec_all_15minuterate{service_name=~\"$servicename\"})by(task_name)",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  { "title": "Leaders", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Max Recorded Leader Election Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(kafka_controller_controllerstats_leaderelectionrateandtimems_max{service_name=~\"$servicename\"})by(service_name)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Unclean Leader Elections (15min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(kafka_controller_controllerstats_uncleanleaderelectionspersec_15minuterate{service_name=~\"$servicename\"})by(service_name)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Avg Time Request Waits for Follower (ms)",
   "type": "graph",
   "description": "Time the request waits for the follower. This is non-zero for produce requests when acks=all",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_network_requestmetrics_remotetimems_mean{service_name=~\"$servicename\"})by(service_name)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Max Lag - Follower/Leader Replicas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 99 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(kafka_server_replicafetchermanager_maxlag{service_name=~\"$servicename\"})by(service_name)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 } },
  {
   "title": "Current Request Queue Size per Broker",
   "type": "graph",
   "description": "Size of the request queue. A congested request queue will not be able to process incoming or outgoing requests",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestchannel_requestqueuesize{service_name=~\"$servicename\"}",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Avg Total Time Request Serve (ms) per Broker",
   "type": "graph",
   "description": "Average total time in ms to serve a specified request",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 107 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_network_requestmetrics_totaltimems_mean{service_name=~\"$servicename\"})by(task_name)",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Avg Request Response Time (ms) per Broker",
   "type": "graph",
   "description": "Time to send the response",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 107 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_network_requestmetrics_responsesendtimems_mean{service_name=~\"$servicename\"})by(task_name)",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Avg Request Waiting Time in Request Queue (ms)",
   "type": "graph",
   "description": "Time the request waits in the request queue",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 116 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_network_requestmetrics_requestqueuetimems_mean{service_name=~\"$servicename\"})by(task_name)",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Avg Request Waiting Time in Response Queue (ms)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 116 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_network_requestmetrics_responsequeuetimems_mean{service_name=~\"$servicename\"})by(task_name)",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Avg Request Processing Time (ms) at Leader",
   "type": "graph",
   "description": "Time the request is processed at the leader",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 116 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_network_requestmetrics_localtimems_mean{service_name=~\"$servicename\"})by(task_name)",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Produce Request Rate / sec (15min) per Broker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 125 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_totalproducerequestspersec_15minuterate{service_name=~\"$servicename\"})by(task_name)",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Fetch Request Rate / sec (15min) per Broker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 125 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_totalfetchrequestspersec_15minuterate{service_name=~\"$servicename\"})by(task_name)",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Produce Request Rate / sec (15min) by (Service / Broker)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 134 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_totalproducerequestspersec_15minuterate{service_name=~\"$servicename\"})by(task_name)",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Fetch Request Rate / sec (15min) by (Service / Broker)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 134 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_totalfetchrequestspersec_15minuterate{service_name=~\"$servicename\"})by(task_name)",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  { "title": "Network Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 143 } },
  {
   "title": "Network Request Rate / sec (15min) by (Service / Broker)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 144 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_fetcherstats_requestspersec_15minuterate{service_name=~\"$servicename\"})by(task_name)",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Network Processor Idle (%)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 144 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_network_processor_idlepercent{service_name=~\"$servicename\"})by(service_name)",
     "legendFormat": "{{service_name}}"
    }
   ]
  }
 ]
}